ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.ApplicationKt.module   # подставь свой package, если изменил

database:
  driverClassName: org.postgresql.Driver
  jdbcUrl: jdbc:postgresql://localhost:5432/codemy?currentSchema=app
  username: codemy_app
  password: CodemySecure2026!
  maximumPoolSize: 10
  autoCommit: false